#AUTOGENERATED! DO NOT EDIT! File to edit: dev/99a_export2html.ipynb (unless otherwise specified).

__all__ = ['remove_widget_state', 'hide_export']

from ..core import *

from ..test import *

from ..imports import *


def remove_widget_state(cell):
    if cell['cell_type'] == 'code' and 'outputs' in cell:
        cell['outputs'] = [l for l in c['outputs']
                           if not ('data' in l and 'application/vnd.jupyter.widget-view+json' in l.data)]
    return cell

def hide_export(cell):
    if check_re(cell, r'^\s*#\s*export\s+'): cell['metadata'] = {'hide_input': True}
    return cell