#AUTOGENERATED! DO NOT EDIT! File to edit: dev/60_audio_core.ipynb (unless otherwise specified).

__all__ = ['audio_extensions', 'get_audio_files', 'AudioGetter']

#Cell 1
from ..torch_basics import *
from ..test import *
from ..data.all import *
from ..notebook.showdoc import *

#Cell 5
audio_extensions = set(k for k,v in mimetypes.types_map.items() if v.startswith('audio/'))

#Cell 6
def get_audio_files(path, recurse=True, include=None):
    "Get audio files in `path` recursively."
    return get_files(path, extensions=audio_extensions, recurse=recurse, include=include)

#Cell 8
def AudioGetter(suf='', recurse=True, include=None):
    "Create `get_audio_files` partial function that searches path suffix `suf` and passes along `kwargs`"
    def _inner(o, recurse=recurse, include=include): return get_audio_files(o/suf, recurse, include)
    return _inner